# Generated by Django 6.0.5 on 2026-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('general', 'general'), ('character', 'character'), ('artist', 'artist'), ('meta', 'meta'), ('ai', 'ai')], default='general', max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000, unique=True)),
                ('thumb_path', models.CharField(blank=True, max_length=1000)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('ai_tagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='gallery.tag')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
