# Generated by Django 6.0.5 on 2026-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='phash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='photo',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
