# Generated by Django 6.0.5 on 2026-05-29 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_fav_photo_phash_photo_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='ai_tagged',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='fav',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('ai_tagged', models.BooleanField(default=False)),
                ('rating', models.SmallIntegerField(default=0)),
                ('fav', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='gallery.tag')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.post'),
        ),
    ]
