# Generated by Django 6.0.5 on 2026-05-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_options_remove_photo_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='not_dupes',
            field=models.ManyToManyField(blank=True, related_name='not_dupes_of', to='gallery.post'),
        ),
    ]
