# Generated by Django 6.0.5 on 2026-05-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_post_not_dupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='not_dupes',
            field=models.ManyToManyField(blank=True, to='gallery.post'),
        ),
    ]
