# Generated by Django 6.0.5 on 2026-05-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_tag_fav_alter_post_not_dupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
