# Generated by Django 6.0.6 on 2026-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='rated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
