# Generated by Django 6.0.6 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_post_faved_at_post_rated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_smart', models.BooleanField(default=False)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='folders', to='gallery.post')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
