# Generated by Django 6.0.5

from django.db import migrations


class Migration(migrations.Migration):
    """Renames Photo.file_path -> rel_path and Photo.thumb_path -> rel_thumb_path.
    This is a pure schema/state rename — no data is touched or lost. Existing
    rows keep whatever value they already had (still an absolute path until
    the "rebase paths" maintenance action converts them to be relative to
    MEDIA_ROOT); Photo.file_path / Photo.thumb_path become Python properties
    (see gallery/models.py) that transparently resolve either form."""

    dependencies = [
        ('gallery', '0010_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file_path',
            new_name='rel_path',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='thumb_path',
            new_name='rel_thumb_path',
        ),
    ]
