# Generated by Django 6.0.5 on 2026-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_folder_include_subfolders'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
