# Generated by Django 6.0.5 on 2026-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0014_task_cancel_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='char_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
