# Generated by Django 6.0.5 on 2026-10-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_post_char_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='char_model',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
