# Generated by Django 6.0.5 on 2026-10-01 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_post_char_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(default='ai', max_length=50)),
                ('threshold', models.FloatField(default=0.7)),
                ('enabled', models.BooleanField(default=True)),
                ('n_pos', models.IntegerField(default=0)),
                ('n_neg', models.IntegerField(default=0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PostFeature',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='gallery.post')),
                ('vec', models.BinaryField()),
                ('model_hash', models.CharField(db_index=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CustomApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gallery.post')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to='gallery.customconcept')),
            ],
            options={
                'unique_together': {('concept', 'post')},
            },
        ),
        migrations.CreateModel(
            name='CustomExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.SmallIntegerField()),
                ('auto', models.BooleanField(default=False)),
                ('feat', models.BinaryField(blank=True, null=True)),
                ('model_hash', models.CharField(blank=True, default='', max_length=40)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='gallery.customconcept')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gallery.post')),
            ],
            options={
                'unique_together': {('concept', 'post')},
            },
        ),
    ]
