# Generated by Django 6.0.5 on 2026-10-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_custom_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_multi',
            field=models.BooleanField(default=False),
        ),
    ]
