# Generated by Django 6.0.5 on 2026-10-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0019_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gen_info',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='source_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_posts', to='gallery.photo'),
        ),
        migrations.AddField(
            model_name='post',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_posts', to='gallery.post'),
        ),
    ]
