from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('duplicates/', views.duplicates, name='duplicates'),
    path('static/js/sw.js', views.service_worker, name='service_worker'),
    path('api/scan/', views.scan, name='scan'),
    path('api/upload/', views.upload, name='upload'),
    path('api/post/<int:pk>/tag/', views.tag_post, name='tag_post'),
    path('api/post/<int:pk>/rate/', views.rate_post, name='rate_post'),
    path('api/post/<int:pk>/delete/', views.delete_post_view, name='delete_post'),
    path('api/post/<int:pk>/ai-tag/', views.ai_tag_post, name='ai_tag_post'),
    path('api/post/<int:pk>/neighbors/', views.post_neighbors, name='post_neighbors'),
    path('api/post/<int:pk>/not-dupes/', views.post_not_dupes, name='post_not_dupes'),
    path('api/bulk/', views.bulk_action, name='bulk_action'),
    path('api/ai-tag-all/', views.ai_tag_all, name='ai_tag_all'),
    path('api/tag-search/', views.tag_search, name='tag_search'),
    path('api/tags/', views.tags_all, name='tags_all'),
    path('api/not-dupe/', views.mark_not_dupe, name='mark_not_dupe'),
    path('random/', views.random_post, name='random_post'),
    path('api/tag/<str:name>/fav/', views.toggle_tag_fav, name='toggle_tag_fav'),
    path('api/image/<int:pk>/delete/', views.delete_image_from_post, name='delete_image'),
    path('api/photo/<int:pk>/delete/', views.delete_photo_view, name='delete_photo'),
    path('api/posts/', views.posts_json, name='posts_json'),
    path('api/merge/', views.merge_posts, name='merge_posts'),
    path('api/organize-merged/', views.organize_existing_merged, name='organize_merged'),
    path('api/prefs/', views.get_prefs, name='get_prefs'),
    path('api/pref/set/', views.set_pref, name='set_pref'),
    path('api/image/<int:pk>/split/', views.split_image, name='split_image'),
    path('api/images/split-to-one/', views.split_images_to_one, name='split_images_to_one'),
    path('api/post/<int:pk>/reorder/', views.reorder_images, name='reorder_images'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]
